CREATE DATABASE  IF NOT EXISTS `projeto`;
USE `projeto`;

DROP TABLE IF EXISTS `doenca_sintoma`;

CREATE TABLE `doenca_sintoma` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `doenca_nome` VARCHAR(255) NOT NULL,
  `sintoma_nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=12;

LOCK TABLES `doenca_sintoma` WRITE;


UNLOCK TABLES;

DROP TABLE IF EXISTS `doencas`;

CREATE TABLE `doencas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=6;

LOCK TABLES `doencas` WRITE;


UNLOCK TABLES;

DROP TABLE IF EXISTS `sintomas`;

CREATE TABLE `sintomas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=7;

LOCK TABLES `sintomas` WRITE;


UNLOCK TABLES;
